name: Run Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script.js
      run: |
        node script.js
      env:
        GITHUB_TOKEN: ${{ secrets.BADDY_AAP_GH_TOKEN }}
