name: Run Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Run script.js
      run: |
        sed -i 's/GITHUB_TOKEN/${{ secrets.BADDY_AAP_GH_TOKEN }}/g' script.js
      env:
        GITHUB_TOKEN: ${{ secrets.BADDY_AAP_GH_TOKEN }}
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.BADDY_AAP_GH_TOKEN }}
        publish_dir: ./  # 
